# gradle.properties
# Project-wide Gradle settings.

org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Explicitly set the JDK home to avoid jlink issues with API 34
# Using forward slashes for better compatibility on Windows
org.gradle.java.home=E:/programs/android/jbr

# Workaround for JdkImageTransform / jlink error on Windows
# Running in process avoids some command line length issues
android.experimental.runJdkImageTransformInProcess=true
